{% set cuda_version='.'.join(environ.get('CUDA_VERSION', '9.2').split('.')[:2]) %}
{% set build = environ.get('BUILD', '0').lstrip('v') %}

package:
    name: blazingsql-dev
    version: 0.4.0

build:
    number: {{ build }}
    string: cuda{{ cuda_version + '_py' + CONDA_PY + '_' + build }}

source:
    path: ../../../

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - cudf
        - pip
        - nvstrings
        - rmm
        - dask-cudf
        - dask
        - gtest
        - gmock
        - setuptools
        - boost-cpp >=1.70.0
        - openssl
        - rapidjson
        - cudatoolkit
        - flatbuffers
        - zlib
        - curl
        - arrow-cpp >=0.14.1
        - libcudf
        - libnvstrings
        - librmm
        - parquet-cpp
        - libhdfs3
        - dask
        - dask-cudf
        - cudatoolkit {{ cuda_version }}.*
        - cmake
        - maven
        - zeromq
    run:
        - python
        - cudf
        - pip
        - nvstrings
        - rmm
        - dask-cudf
        - dask
        - gtest
        - gmock
        - setuptools
        - boost-cpp >=1.70.0
        - openssl
        - rapidjson
        - cudatoolkit
        - flatbuffers
        - zlib
        - curl
        - arrow-cpp >=0.14.1
        - libcudf
        - libnvstrings
        - librmm
        - parquet-cpp
        - libhdfs3
        - dask
        - dask-cudf
        - cudatoolkit {{ cuda_version }}.*
        - cmake
        - maven
        - zeromq
about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
