{% set build = environ.get('BUILD', '0').lstrip('v') %}

package:
    name: blazingdb-toolchain
    version: 0.4.0

build:
    number: {{ build }}

source:
    path: ../../../

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    host:
        - python
        - pip
        - gtest
        - gmock
        - setuptools
        - boost-cpp >=1.70.0
        - openssl
        - zlib
        - curl
        - cmake
    run:
        - python
        - pip
        - gtest
        - gmock
        - setuptools
        - boost-cpp >=1.70.0
        - openssl
        - zlib
        - curl
        - cmake

about:
    home: http://www.blazingsql.com/
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
